import * as assert from "node:assert/strict";
import * as path from "node:path";
import * as vscode from "vscode";

suite("Arduino Unified Comprehensive Test Suite", () => {
  vscode.window.showInformationMessage("Starting comprehensive tests...");

  suite("Phase 1: Core Extension Verification", () => {
    test("Extension context resolves without crashing", async () => {
      const ext = vscode.extensions.getExtension(
        "fermeridamagni.arduino-unified"
      );
      assert.ok(ext, "Extension fermeridamagni.arduino-unified not found!");
    });
  });

  suite("Phase 2: ArduinoDaemon Parser Verifications", () => {
    const DAEMON_REGEX = /"[pP]ort"\s*:\s*"?(\d+)"?/;

    test("Daemon Regex flawlessly parses direct flat JSON targets", () => {
      const directJson = '{"IP":"127.0.0.1","Port":"50051"}';
      const match = directJson.match(DAEMON_REGEX);
      assert.ok(match, "Regex failed to evaluate string.");
      assert.strictEqual(match?.[1], "50051");
    });

    test("Daemon Regex accurately tracks spaced JSON formats generated by recent CLI runtimes", () => {
      const spacerJson = '{\n  "IP": "127.0.0.1",\n  "port": 50051\n}';
      const match = spacerJson.match(DAEMON_REGEX);
      assert.ok(match, "Regex failed to evaluate spaced JSON format.");
      assert.strictEqual(match?.[1], "50051");
    });

    test("Daemon Regex operates resiliently handling string coercions unexpectedly", () => {
      const looseJson = '{\n  "Port":   "50422" \n}';
      const match = looseJson.match(DAEMON_REGEX);
      assert.ok(match, "Regex failed to evaluate un-constrained string maps");
      assert.strictEqual(match?.[1], "50422");
    });
  });

  suite("Phase 3: Directory Schema Constraint Engine Mapping", () => {
    test("Schema mathematically evaluates Arduino C++ conformity identically to the native logic", () => {
      const mockPathPosix = "/Users/test/projects/Blink/Blink.ino";
      const sketchDir = path.dirname(mockPathPosix);
      const sketchDirName = path.basename(sketchDir);
      const isStandard =
        path.basename(mockPathPosix) === `${sketchDirName}.ino`;

      assert.strictEqual(
        isStandard,
        true,
        "Standard valid mapping was flagged as non-conforming falsely"
      );
    });

    test("Schema immediately trips safety nets on non-conforming isolated entry points", () => {
      const mockPathPosix = "/Users/test/projects/Blink/main.ino";
      const sketchDir = path.dirname(mockPathPosix);
      const sketchDirName = path.basename(sketchDir);
      const isStandard =
        path.basename(mockPathPosix) === `${sketchDirName}.ino`;

      assert.strictEqual(
        isStandard,
        false,
        "Schema missed non-conforming main.ino map!"
      );

      // Test our auto-rename fallback logic!
      const suggestedRenameTarget = path.join(
        sketchDir,
        `${sketchDirName}.ino`
      );
      // Normalize paths for cross-platform testing (Windows uses backslashes)
      const expected = path.posix.join("/Users/test/projects/Blink", "Blink.ino");
      assert.strictEqual(
        path.normalize(suggestedRenameTarget).replace(/\\/g, "/"),
        expected
      );
    });
  });
});
