import * as vscode from "vscode";

/**
 * Provides syntax highlighting and language configuration for .ino files.
 * Treats .ino files as C++ with Arduino-specific additions.
 */
export function registerLanguageSupport(
  context: vscode.ExtensionContext
): void {
  // Register .ino as a language associated with C++
  // This gives us C++ highlighting out-of-the-box
  context.subscriptions.push(
    vscode.workspace.onDidOpenTextDocument((doc) => {
      if (doc.fileName.endsWith(".ino") || doc.fileName.endsWith(".pde")) {
        vscode.languages.setTextDocumentLanguage(doc, "cpp");
      }
    })
  );

  // Set language for already-open .ino files
  for (const doc of vscode.workspace.textDocuments) {
    if (doc.fileName.endsWith(".ino") || doc.fileName.endsWith(".pde")) {
      vscode.languages.setTextDocumentLanguage(doc, "cpp");
    }
  }

  // Register file associations
  const fileAssociations = vscode.workspace.getConfiguration("files");
  const existingAssociations = fileAssociations.get<Record<string, string>>(
    "associations",
    {}
  );

  if (!existingAssociations["*.ino"]) {
    const updated = { ...existingAssociations, "*.ino": "cpp", "*.pde": "cpp" };
    fileAssociations.update(
      "associations",
      updated,
      vscode.ConfigurationTarget.Global
    );
  }

  // Register hover provider for Arduino-specific keywords
  context.subscriptions.push(
    vscode.languages.registerHoverProvider(
      { scheme: "file", pattern: "**/*.{ino,pde}" },
      new ArduinoHoverProvider()
    )
  );

  // Register completion provider for Arduino-specific items
  context.subscriptions.push(
    vscode.languages.registerCompletionItemProvider(
      { scheme: "file", pattern: "**/*.{ino,pde}" },
      new ArduinoCompletionProvider(),
      "."
    )
  );
}

/**
 * Arduino keyword documentation for hover tooltips.
 */
const ARDUINO_KEYWORDS: Record<string, string> = {
  pinMode:
    "`pinMode(pin, mode)`\n\nConfigures a pin as INPUT, OUTPUT, or INPUT_PULLUP.\n\n- **pin**: the pin number\n- **mode**: INPUT, OUTPUT, or INPUT_PULLUP",
  digitalWrite:
    "`digitalWrite(pin, value)`\n\nWrite HIGH or LOW to a digital pin.\n\n- **pin**: the pin number\n- **value**: HIGH or LOW",
  digitalRead:
    "`digitalRead(pin)`\n\nReads the value from a digital pin (HIGH or LOW).\n\n- **pin**: the pin number\n- **Returns**: HIGH or LOW",
  analogRead:
    "`analogRead(pin)`\n\nReads the analog value from a pin (0-1023).\n\n- **pin**: the analog pin number\n- **Returns**: int (0-1023)",
  analogWrite:
    "`analogWrite(pin, value)`\n\nWrites an analog value (PWM) to a pin.\n\n- **pin**: the PWM pin number\n- **value**: 0-255",
  delay:
    "`delay(ms)`\n\nPauses the program for a specified time in milliseconds.\n\n- **ms**: milliseconds to pause",
  delayMicroseconds:
    "`delayMicroseconds(us)`\n\nPauses the program for a specified time in microseconds.\n\n- **us**: microseconds to pause",
  millis:
    "`millis()`\n\nReturns the number of milliseconds since the board began running.\n\n- **Returns**: unsigned long",
  micros:
    "`micros()`\n\nReturns the number of microseconds since the board began running.\n\n- **Returns**: unsigned long",
  Serial:
    "Serial communication object.\n\nCommon methods:\n- `Serial.begin(baudRate)` — Start serial communication\n- `Serial.print(data)` — Print data\n- `Serial.println(data)` — Print data with newline\n- `Serial.read()` — Read incoming byte\n- `Serial.available()` — Check for available data",
  setup:
    "`void setup()`\n\nCalled once when the sketch starts. Use it to initialize variables, pin modes, start libraries, etc.",
  loop: "`void loop()`\n\nCalled repeatedly after setup(). This is where you put your main code.",
  HIGH: "Logic level HIGH (1, 5V or 3.3V depending on the board)",
  LOW: "Logic level LOW (0, 0V)",
  INPUT: "Pin mode: high-impedance input",
  OUTPUT: "Pin mode: output (can source/sink current)",
  INPUT_PULLUP: "Pin mode: input with internal pull-up resistor enabled",
  LED_BUILTIN: "Built-in LED pin number (usually 13)",
  attachInterrupt:
    "`attachInterrupt(digitalPinToInterrupt(pin), ISR, mode)`\n\nAttaches an interrupt handler.\n\n- **pin**: interrupt pin\n- **ISR**: interrupt service routine function\n- **mode**: RISING, FALLING, CHANGE, LOW, HIGH",
  tone: "`tone(pin, frequency, duration)`\n\nGenerates a square wave on a pin.\n\n- **pin**: output pin\n- **frequency**: Hz\n- **duration**: (optional) ms",
  noTone: "`noTone(pin)`\n\nStops the tone generated by tone().",
  map: "`map(value, fromLow, fromHigh, toLow, toHigh)`\n\nRe-maps a number from one range to another.\n\n- **Returns**: long",
  constrain:
    "`constrain(x, a, b)`\n\nConstrains a number between a and b.\n\n- **Returns**: x if a ≤ x ≤ b, a if x < a, b if x > b",
};

/**
 * Provides hover documentation for Arduino keywords.
 */
class ArduinoHoverProvider implements vscode.HoverProvider {
  provideHover(
    document: vscode.TextDocument,
    position: vscode.Position
  ): vscode.ProviderResult<vscode.Hover> {
    const wordRange = document.getWordRangeAtPosition(position);
    if (!wordRange) {
      return null;
    }

    const word = document.getText(wordRange);
    const doc = ARDUINO_KEYWORDS[word];

    if (doc) {
      const markdown = new vscode.MarkdownString(doc);
      markdown.isTrusted = true;
      return new vscode.Hover(markdown, wordRange);
    }

    return null;
  }
}

/**
 * Provides Arduino-specific code completions.
 */
class ArduinoCompletionProvider implements vscode.CompletionItemProvider {
  provideCompletionItems(
    document: vscode.TextDocument,
    position: vscode.Position
  ): vscode.ProviderResult<vscode.CompletionItem[]> {
    const linePrefix = document
      .lineAt(position)
      .text.substring(0, position.character);

    // Serial. completions
    if (linePrefix.endsWith("Serial.")) {
      return this.getSerialCompletions();
    }

    // General Arduino function completions
    return this.getArduinoCompletions();
  }

  private getSerialCompletions(): vscode.CompletionItem[] {
    const methods = [
      {
        name: "begin",
        snippet: "begin(${1:9600})",
        detail: "Start serial communication",
      },
      {
        name: "print",
        snippet: "print(${1:data})",
        detail: "Print data to serial",
      },
      {
        name: "println",
        snippet: "println(${1:data})",
        detail: "Print data with newline",
      },
      { name: "read", snippet: "read()", detail: "Read incoming byte" },
      {
        name: "available",
        snippet: "available()",
        detail: "Check available bytes",
      },
      {
        name: "write",
        snippet: "write(${1:data})",
        detail: "Write binary data",
      },
      {
        name: "flush",
        snippet: "flush()",
        detail: "Wait for transmission to complete",
      },
      {
        name: "parseInt",
        snippet: "parseInt()",
        detail: "Read integer from serial",
      },
      {
        name: "parseFloat",
        snippet: "parseFloat()",
        detail: "Read float from serial",
      },
      {
        name: "readString",
        snippet: "readString()",
        detail: "Read string from serial",
      },
      {
        name: "setTimeout",
        snippet: "setTimeout(${1:1000})",
        detail: "Set timeout for reads",
      },
    ];

    return methods.map((m) => {
      const item = new vscode.CompletionItem(
        m.name,
        vscode.CompletionItemKind.Method
      );
      item.insertText = new vscode.SnippetString(m.snippet);
      item.detail = m.detail;
      return item;
    });
  }

  private getArduinoCompletions(): vscode.CompletionItem[] {
    const functions = [
      {
        name: "pinMode",
        snippet: "pinMode(${1:pin}, ${2|INPUT,OUTPUT,INPUT_PULLUP|})",
        kind: vscode.CompletionItemKind.Function,
      },
      {
        name: "digitalWrite",
        snippet: "digitalWrite(${1:pin}, ${2|HIGH,LOW|})",
        kind: vscode.CompletionItemKind.Function,
      },
      {
        name: "digitalRead",
        snippet: "digitalRead(${1:pin})",
        kind: vscode.CompletionItemKind.Function,
      },
      {
        name: "analogRead",
        snippet: "analogRead(${1:pin})",
        kind: vscode.CompletionItemKind.Function,
      },
      {
        name: "analogWrite",
        snippet: "analogWrite(${1:pin}, ${2:value})",
        kind: vscode.CompletionItemKind.Function,
      },
      {
        name: "delay",
        snippet: "delay(${1:ms})",
        kind: vscode.CompletionItemKind.Function,
      },
      {
        name: "millis",
        snippet: "millis()",
        kind: vscode.CompletionItemKind.Function,
      },
      {
        name: "attachInterrupt",
        snippet:
          "attachInterrupt(digitalPinToInterrupt(${1:pin}), ${2:ISR}, ${3|RISING,FALLING,CHANGE|})",
        kind: vscode.CompletionItemKind.Function,
      },
      {
        name: "map",
        snippet:
          "map(${1:value}, ${2:fromLow}, ${3:fromHigh}, ${4:toLow}, ${5:toHigh})",
        kind: vscode.CompletionItemKind.Function,
      },
      {
        name: "constrain",
        snippet: "constrain(${1:x}, ${2:a}, ${3:b})",
        kind: vscode.CompletionItemKind.Function,
      },
      {
        name: "tone",
        snippet: "tone(${1:pin}, ${2:frequency})",
        kind: vscode.CompletionItemKind.Function,
      },
      {
        name: "noTone",
        snippet: "noTone(${1:pin})",
        kind: vscode.CompletionItemKind.Function,
      },
    ];

    return functions.map((f) => {
      const item = new vscode.CompletionItem(f.name, f.kind);
      item.insertText = new vscode.SnippetString(f.snippet);
      item.detail = `Arduino: ${f.name}`;
      return item;
    });
  }
}
